theme: jekyll-theme-minimal
title: Andrews Ata Kangah
description: I am Andres Ata Kangah, a mobile and web developer interested in increasing my knowledge while having fun as well. I build web apps and mobile apps using Angular Framework and React Js. I also build Native Android Mobile apps using Java, and cross-platform mobile apss using React Native. 
